### ISSUE TITLE
cv2.COLOR_RGB2GRAY

### ISSUE THREAD

**Issue by yjwtt** [TalentBoy2333/VideoSAR-segmentation#1]
你好，请问我在运行fcn.py时候报这个错是怎么回事cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:9748: error: (-215) scn == 3 || scn == 4 in function cv::cvtColor 是数据色彩转化那儿的问题cv2.COLOR_RGB2GRAY

**Comment by TalentBoy2333** [comment]
可能是程序在读图的时候，图片本来就是灰度图，再运行rgb2gray就会报错，不好意思，这几个月搞别的东西去了，没上过Github。。不要怪我呜呜呜。。现在代码已经被我改的面目全非了，，换成pytorch版本的了，，我用了3D卷积和LSTM

**Comment by yjwtt** [comment]
谢谢 还有一个问题： 视频转成的图像不是（720，660），去掉两边的黑边才是，需不需要用处理视频的软件去黑边

**Comment by TalentBoy2333** [comment]
是的，需要编程处理一下，我用的cv2

**Comment by yjwtt** [comment]
好的谢谢

**Comment by yjwtt** [comment]
你好! 我运行这个程序的时候 dataset/segmentation里缺标签， 文件夹里只有一张。   我自己尝试标标签， 但标的很不准确， 能不能把你的标签分享给我?  万分感谢!

**Comment by TalentBoy2333** [comment]
标签在学校电脑里，等疫情结束，回去了给你个百度云链接吧

**Comment by yjwtt** [comment]
好的  太感谢了

**Comment by yjwtt** [comment]
你好 我在标数据集的时候有的目标不明显 标的有很多失误  请问你是这么标的吗？

**Comment by TalentBoy2333** [comment]
标注一个视频帧的同时可以参考之前和之后的帧，另外，轮廓标的不准确没关系（'Segmentation Is All You Need'这篇论文里指出的，可以参考一下）

**Comment by yjwtt** [comment]
好的 我尝试标一下先 谢谢

**Comment by yjwtt** [comment]
学长这是我的邮箱： 278701713@qq.com   十分感谢
